[package]
name = "steamcleaner"
version = "0.0.1"
authors = ["Vytrol"]
edition = "2021"

[dependencies]
colored = "2.0.4"
dont_disappear = "3.0.1"
lazy_static = "1.4.0"
privilege = "0.3.0"
sysinfo = "0.29.10"
winreg = "0.51.0"
